version: '3.8'

services:
  campusgrid:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: campusgrid
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
